LoginRadius/apidocs

database/apidocs/docs/v2/admin-console/deployment/custom-domain-and-ssl-configuration.md

Minor Updates (Pipeline Test)

---

database/apidocs/docs/v2/admin-console/platform-configuration/standard-login/multiple-smtp-domain.md

Replace the **"Multiple SMTP"** phrase with **"Multiple SMTP Domain"** along with minor logical & grammatical corrections.

Corrected the document for Multiple SMTP Domain feature

---

database/supportdocs/docs/libraries/mobile-sdk-libraries/ios-library.md

Replaced the existing **ios-library.md** file with the updated version provided by the **Implementation team** via **DOC-2496**.

Update the iOS API document

---

database/supportdocs/docs/single-sign-on/concept/oidc-providers/azure-ad-b2c.md

Corrected the heading in **Azure B2C document**. Below are the changes:
- Steps To configure LoginRadius as IDP in Azure ~in Azure~

Corrected a heading in Azure document

---

database/supportdocs/docs/libraries/sdk-libraries/php-library.md

Updated PHP SDK document using **README.txt** file provided by the **Implementation team** in **DOC-2503**.

Updated PHP SDK document

---

database/apidocs/docs/v2/admin-console/team-management/audit-logs.md

Added a note in the Audit Logs document.

Add a Note in Audit Logs document

---

database/supportdocs/docs/libraries/js-libraries/javascript-hooks.md

document updated as per doc task 2507

document updated as per doc task 2507

---

database/apidocs/docs/v2/customer-identity-api/social-login/getting-started.md

Made corrections

---

database/supportdocs/docs/single-sign-on/concept/saml-providers/sharepoint.md

Minor correction in SharePoint documents

Minor correction in SharePoint documents

---

database/apidocs/docs/v2/admin-console/deployment/site-configurations-sync.md

Minor changes have been made in the wording.

Review configuration deployment document.

---

database/supportdocs/docs/authentication/concepts/email-verification-workflow.md

We have added a note in the documents

Add Note In Email-Verification Workflow.

---

database/supportdocs/docs/customer-intelligence/comparative-analysis.md
database/supportdocs/docs/customer-intelligence/identity-analytics.md
database/supportdocs/docs/customer-intelligence/login-analytics.md
database/supportdocs/docs/customer-intelligence/provider-analytics.md

We have added Steps to download Insights in the documents

Add Steps To Download Insights

---

database/supportdocs/docs/libraries/js-libraries/js-form-library.md

Updating the note on forget password flow document.

Updated the note on Forget Password Flow Document.

---

database/supportdocs/docs/libraries/js-libraries/js-form-library.md

Updating the Note on Forget Password Flow Document.

Updated the note on forget password flow document

---

database/supportdocs/docs/security/platform-security/account-verification-overview.md

Removed the block of fraudulent domains from one document.

Removed Block Fraudulent Domains From one document.

---

database/supportdocs/docs/security/platform-security/identity-data-compliance.md

Updated Broken links Related to COPPA.

Monthly Link Check Updates

---

database/supportdocs/menus/sidebar.json
plugins/routing/redirections/urls.json

Merged two documents with redirections as well

Merge of Documents on SMS Provider

---

database/supportdocs/docs/integrations/available-integrations.md

Uploaded the images on lrcontent.com

Updated the images on lrcontent.com

---

database/supportdocs/docs/integrations/available-integrations.md

uploaded the images on lrcontent.com

uploaded the images on lrcontent.com

---

database/apidocs/apis/v2/authentication/configuration/get-configurations.json
database/apidocs/apis/v2/customer-identity-api/configuration/get-configurations.json
database/apidocs/docs/v2/announcements/facebook-enforce-https.md
database/apidocs/docs/v2/customer-identity-api/social-login/getting-started.md
database/supportdocs/docs/customer-intelligence/identity-analytics.md
database/supportdocs/docs/libraries/js-libraries/advanced-js-customizations.md
database/supportdocs/docs/libraries/js-libraries/getting-started.md
orphaned/social-login/advanced-customization-social.md

Updated RequestHandlor URL to New the format RequestHandler.

Updated RequestHandler URLs

---

database/apidocs/docs/v2/admin-console/social-provider/social-provider-overview.md
database/apidocs/menus/v2.json
database/supportdocs/docs/governance/configure-social-data-settings.md
plugins/routing/redirections/urls.json

We have removed and merged duplicate documents.

Remove/ Merge the document of Social Data Settings

---

database/apidocs/docs/v2/admin-console/social-provider/social-provider-overview.md
database/apidocs/menus/v2.json
plugins/routing/redirections/urls.json

We have Merged and remove the dupliicate documents for advance data points.

Remove/Merge the document of Advanced Data-points

---

database/apidocs/apis/v2/single-sign-on/federated-sso/jwt-login/jwt-token.json
database/apidocs/docs/v2/getting-started/acceptable-use-policy.md

The following actions have been performed in this merge:
- Updated the **Acceptable Use Policy** document with the latest verified version from Tier 2.
- Update the description of the `access_token` in **JWT Token by Access Token API**.

Update Acceptable Use Policy & API Parameter description

---

database/apidocs/apis/v2/cloud-directory-api/custom-object/get-custom-objects.json

Post DDoS Task Link correction 1

---

database/apidocs/docs/v2/customer-identity-api/passwordless-login/passwordless-login-overview.md
database/apidocs/menus/v2.json
database/supportdocs/docs/authentication/tutorial/passwordless-login.md
plugins/routing/redirections/urls.json

Removed and merged duplicate documents related to Passwordless login and also handled the redirections

Removed and Merged Duplicate Documents on Passwordless Login

---

database/apidocs/changelog/admin-console-release-25102.json

Corrected capitalizations and improved sentence formulations in the changelog.

Admin Console Release 25.10.2 (Amendments)

---

theme/apidocs/home.php

Updating our documentation theme back to the **Rocket Theme**.

Updated the documentation theme

---

database/apidocs/docs/v2/admin-console/team-management/sso-connectors/SAML.md
database/apidocs/docs/v2/admin-console/team-management/sso-connectors/adfs-setup-in-admin-console.md
database/apidocs/docs/v2/admin-console/team-management/sso-connectors/salesforce.md
database/apidocs/docs/v2/admin-console/team-management/sso-connectors/setup-azure-ad.md

We have updated the Documents according to new Admin Console release for Team SSO.

Document updated according to new Admin Console release

---

theme/apidocs/home.php

Updating our documentation theme to the **Christmas Theme**

Updated documentation theme

---

plugins/routing/redirections/urls.json

Fixed the redirections in this task. (Re-correction while verifying)

Fixed 404 Redirections

---

database/apidocs/docs/v2/admin-console/platform-configuration/standard-login/Overview.md
database/apidocs/menus/v2.json

Document updated on Standard Login Fields

---

database/supportdocs/docs/libraries/turn-key-plugins/wordpress-2-x-plugin.md

We have updated the wordpress version in wordpress document.

Updated the version in WordPress document

---

plugins/routing/redirections/urls.json

Made some changes in redirection link

---

database/supportdocs/docs/libraries/sdk-libraries/asp-net-library.md
plugins/routing/redirections/urls.json

We have reupdated the redirection links

Updated the links and redirections

---

plugins/routing/redirections/urls.json

We have added a redirection link.

Redirection Handled for 404

---

plugins/routing/redirections/urls.json

Fix resolve conflicts

---

database/supportdocs/docs/authentication/quick-start/social-login.md
plugins/routing/redirections/urls.json

Transformed links from Capital to small letters

Fixed issues having 404 error

---

plugins/routing/redirections/urls.json

SAML redirection fix

---

database/supportdocs/docs/libraries/sdk-libraries/coldfusion-library.md
plugins/routing/redirections/urls.json

Fixed the 404 link in coldfusion library

---

database/supportdocs/docs/authentication/concepts/email-verification-workflow.md

Updated screenshots with respect to admin console release 25.10.5

Updated screenshots with respect to admin console release 25.10.5

---

database/supportdocs/docs/authentication/concepts/email-verification-workflow.md
database/supportdocs/docs/customer-management/self-serve-data-migration.md

The following are the changes done in this merge.
- Replaced the word **customer** with **consumer**.
- Removed a left over reference to the **deprecated Data ETL** feature.
- Updated the content in the Email Verification flow documentation as per the new UI.

Updated the content as per the Admin Console release

---

database/apidocs/docs/v2/admin-console/platform-security/captcha-providers/google-recaptcha-configuration.md
database/apidocs/docs/v2/admin-console/platform-security/captcha-providers/tencent-captcha-configuration.md
database/supportdocs/docs/authentication/concepts/customer-security.md

Split CAPTCHA content into **Conceptual** and **Configuration & Deployment** and **interlinked** the documents.

Split CAPTCHA content

---

theme/apidocs/home.php

We have reverted the theme back to Rocket one.

Updated the Theme to Rocket theme

---

database/apidocs/docs/v2/admin-console/platform-security/api-security.md

We have depricated the optional recaptcha configuration Document.

Depricated the optional recaptcha configurations.

---

database/apidocs/docs/v2/customer-identity-api/social-login/getting-started.md
database/apidocs/menus/v2.json
database/supportdocs/docs/libraries/js-libraries/js-form-library.md

Removed the references & content associated with deprecated social data endpoints.

Removed the references for deprecated endpoints

---

database/apidocs/docs/v2/admin-console/deployment/site-configurations-sync.md
database/apidocs/docs/v2/admin-console/platform-configuration/Overview.md
database/apidocs/docs/v2/admin-console/team-management/audit-logs.md
database/supportdocs/docs/security/data-management/confidentiality-integrity-and-availability.md

We have modified Documents which mentioned bot protection

Removal of Bot Protection Documents

---

database/supportdocs/docs/security/infrastructure/ip-addresses-list.md

Updated the IP List

---

config.php
plugins/dev-stag-protect/protect.php

added domain

---

config.php
plugins/dev-stag-protect/protect.php

Reverts LoginRadius/apidocs#147

Revert "added domain"

---

config.php

Reverts LoginRadius/apidocs#144

Revert "Update config.php"

---

database/supportdocs/menus/sidebar.json
plugins/routing/redirections/urls.json

Remove the WS Federation Provider & handled their redirection

Removed_the_WS_Federation_Provider

---

config.php

Equating Production Push merged by Kailash to resolve redirection issue with this Dev Push.

Equating Production Push with this Dev Push

---

database/apidocs/docs/v2/admin-console/team-management/sso-connectors/overview.md
database/apidocs/docs/v2/admin-console/team-management/sso-connectors/setup-azure-ad.md

I have updated the Documents according to new changes in the Admin Console.

Document updatation regarding Azure AD

---

database/supportdocs/docs/libraries/identity-experience-framework/customization.md
database/supportdocs/docs/libraries/mobile-sdk-libraries/ios-library.md

Added x-frame-options in documentation &_removed the unwanted line in the ios document.

Added_x-frame-options_&_removed_unwanted_line

---

database/supportdocs/docs/single-sign-on/concept/saml-providers/domo.md
database/supportdocs/docs/single-sign-on/concept/saml-providers/jira.md
database/supportdocs/docs/single-sign-on/concept/saml-providers/office365.md
database/supportdocs/docs/single-sign-on/concept/saml-providers/salesforce.md
database/supportdocs/docs/single-sign-on/concept/saml-providers/sharepoint.md
database/supportdocs/docs/single-sign-on/tutorial/federated-sso/saml/idp-initiated.md
database/supportdocs/docs/single-sign-on/tutorial/federated-sso/saml/sp-initiated.md

All the changes are made as per requirement (notes are added)

Update the LoginRadius as IDP with Salesforce as SP

---

database/apidocs/docs/v2/admin-console/deployment/site-configurations-sync.md
database/apidocs/docs/v2/admin-console/platform-configuration/Overview.md
database/apidocs/docs/v2/admin-console/platform-security/api-security.md
database/apidocs/docs/v2/admin-console/team-management/audit-logs.md
database/supportdocs/docs/security/data-management/confidentiality-integrity-and-availability.md

We had to renable the recaptcha feature. So we have added in docs.

AddOptionalRecaptcha

---

database/apidocs/docs/v2/admin-console/platform-security/api-security.md

Updated the description and the screenshot in step 3.

Update the API Security document to conform to the Admin Console Release 25.10.8.

---

database/apidocs/docs/v2/admin-console/platform-security/api-security.md

Updated the screenshot in Step 2 for the associated document.

Updated the API Security document to conform to the Admin Console Release 25.10.8

---

plugins/routing/redirections/urls.json

Corrected the redirection of FAQ

FAQLinkCorrection

---

database/supportdocs/docs/single-sign-on/tutorial/federated-sso/oauth-2-0/oauth-2-0-overview.md

Updates as per new interface

---

database/supportdocs/docs/integrations/available-integrations.md

Added Mulesoft in integrations

---

database/apidocs/apis/v2/single-sign-on/federated-sso/openid-connect/request-device-code.json

Update the endpoint to correct value.

Update the endpoint

---

database/supportdocs/docs/integrations/available-integrations.md

Updated the mulesoft icon as per maintained flow.

Updated the mulesoft icon

---

database/apidocs/docs/v2/announcements/cli.md
database/apidocs/menus/v2.json

CLI document created as per CLI manual

Created the CLI document

---

database/apidocs/changelog/cli-release-v2.0.2.json
database/apidocs/menus/posts.json

Prepared the Chnagelog for CLI beta v2.0.2

Prepared Changelog

---

database/apidocs/changelog/cli-release-v2.0.2.json

Made some changes to fix an issue.

Made some necessary changes

---

plugins/routing/redirections/urls.json

Removed the redirection URL which was causing the issue.

Updated the redirection URL

---

plugins/routing/redirections/urls.json

Handled the redirection of the Developer pages

Handled the redirection

---

database/supportdocs/docs/single-sign-on/tutorial/federated-sso/openid-connect/openid-connect-overview.md

Updated the Device Code Flow section

Made changes as per new OIDC Flow

---

database/apidocs/apis/v2/customer-identity-api/refresh-token/revoke-all-refresh-token.json
database/apidocs/menus/v2.json

New API for revoking all refresh token.

New API Added

---

database/supportdocs/docs/libraries/mobile-sdk-libraries/ios-library.md

Updated the IOS SDK to new version.

---

database/apidocs/docs/v2/customer-identity-api/account/account-overview.md
database/supportdocs/docs/authentication/concepts/customer-security.md

Added_details_about_management_api's

Added_details_about_management_API's

---

database/supportdocs/docs/integrations/third-party-integration-platforms/overview.md

Corrected a few spelling mistakes and added a link to the support ticket section

Minor spelling correction in the document

---

database/apidocs/apis/v2/single-sign-on/federated-sso/saml/saml-meta-data.json
database/supportdocs/docs/single-sign-on/concept/saml-providers/domo.md
database/supportdocs/docs/single-sign-on/concept/saml-providers/jira.md
database/supportdocs/docs/single-sign-on/concept/saml-providers/office365.md
database/supportdocs/docs/single-sign-on/concept/saml-providers/salesforce.md
database/supportdocs/docs/single-sign-on/concept/saml-providers/sharepoint.md
database/supportdocs/docs/single-sign-on/tutorial/federated-sso/saml/idp-initiated.md
database/supportdocs/docs/single-sign-on/tutorial/federated-sso/saml/overview.md
database/supportdocs/docs/single-sign-on/tutorial/federated-sso/saml/sp-initiated.md
database/supportdocs/docs/single-sign-on/tutorial/web-sso/overview.md

Updated the SAML endpoints and output format

Updated SAML enpoints

---

database/apidocs/docs/v2/admin-console/platform-security/api-key-and-secret.md
database/supportdocs/docs/integrations/webhook.md

Updated the API Key & Secret and Webhook documentation to conform to the UI changes as part of Admin Console release 25.10.9

Update document to conform to UI changes

---

database/supportdocs/docs/integrations/webhook.md

Minor spelling corrections

---

database/apidocs/docs/v2/admin-console/deployment/site-configurations-sync.md

Made minor formatting changes in a note.

Minor formating needed.

---

database/apidocs/docs/v2/customer-identity-api/pin-authentication/overview.md

Did_ui_changes_for_pinlogin_button

Did_ui_changes_for_pinlogin_added_button

---

database/apidocs/changelog/js-release-3200.json
database/apidocs/menus/posts.json

Changelog for JS release 3.20.0

JS release 3.20.0 changelog

---

database/apidocs/changelog/core-api-release-3590.json
database/apidocs/menus/posts.json

Core_API_Release_35.9.0

---

database/apidocs/apis/v2/customer-identity-api/authentication/auth-invalidate-access-token.json
database/apidocs/apis/v2/customer-identity-api/authentication/auth-reset-password-by-email.json
database/apidocs/apis/v2/customer-identity-api/authentication/auth-reset-password-by-phone.json
database/apidocs/apis/v2/customer-identity-api/authentication/auth-reset-password-by-username.json
database/apidocs/apis/v2/customer-identity-api/authentication/auth-validate-access-token.json
database/apidocs/menus/v2.json

Review_all_the_Authentication_APIs

Chenged_api_names_as_per_the_spec_docs

---

database/supportdocs/docs/security/infrastructure/ip-addresses-list.md

New IPs that need to be whitelisted are added

New IPs added

---

database/supportdocs/docs/single-sign-on/concept/saml-providers/office365.md

The APP AUDIENCES value is updated.

App Audiences value updated

---

database/apidocs/changelog/admin-console-release-25109.json
database/supportdocs/docs/authentication/concepts/ui-ux-customizations-idx.md
database/supportdocs/docs/libraries/identity-experience-framework/customization.md
theme/apidocs/includes/footer.php

Resolving conflicts

---

database/supportdocs/docs/authentication/faq/account-linking.md

Testing Conflicts Resolution

---

database/apidocs/docs/v2/admin-console/team-management/sso-connectors/Saml.md
database/apidocs/docs/v2/admin-console/team-management/sso-connectors/adfs-setup-in-admin-console.md
database/apidocs/docs/v2/admin-console/team-management/sso-connectors/salesforce.md
database/apidocs/docs/v2/admin-console/team-management/sso-connectors/setup-azure-ad.md
database/supportdocs/docs/single-sign-on/tutorial/custom-identity-providers/custom-adfs-provider.md
database/supportdocs/docs/single-sign-on/tutorial/custom-identity-providers/custom-saml-provider.md
database/supportdocs/docs/single-sign-on/tutorial/federated-sso/saml/idp-initiated.md
database/supportdocs/docs/single-sign-on/tutorial/federated-sso/saml/sp-initiated.md

Added_note_and_image

---

plugins/routing/redirections/urls.json

Added redirection for hCaptcha

---

database/apidocs/apis/v2/customer-identity-api/authentication/auth-login-by-username.json
database/apidocs/apis/v2/customer-identity-api/authentication/auth-validate-access-token.json
database/apidocs/apis/v2/customer-identity-api/authentication/auth-verify-email-by-otp.json
database/apidocs/apis/v2/customer-identity-api/authentication/auth-verify-email.json
database/apidocs/docs/v2/customer-identity-api/refresh-token/overview.md

Updated the Sample payloads and added note.

API responses and note has been added.

---

database/apidocs/docs/v2/admin-console/profile-management/data-export.md

Percy Test on S3 bucket

---

database/supportdocs/docs/customer-management/customer-segmentation/basic-segmentation.md

Percy Test S3 bucket 1

---

database/apidocs/changelog/core-api-release-3590.json
database/apidocs/changelog/core-api-release-3600.json
database/apidocs/docs/v2/customer-identity-api/refresh-token/overview.md
database/apidocs/menus/posts.json

Core_API_Release_3600

---

database/apidocs/changelog/core-api-release-3590.json
database/apidocs/changelog/core-api-release-3600.json
database/apidocs/docs/v2/customer-identity-api/refresh-token/overview.md
database/apidocs/menus/posts.json

Direct Merge for DOC-2671

---

database/apidocs/changelog/core-api-release-3590.json

added link in Core API Release 36.0.0

added-link

---

database/supportdocs/docs/security/data-management/loginradius-tokens.md

details about JWT as token has been added.

JWT as token document added

---

database/apidocs/docs/v2/admin-console/platform-configuration/communication-configuration/sms/overview.md
database/supportdocs/docs/authentication/concepts/sms-communication.md

OTP via Voice SMS configuration-related changes

OTP_via_Voice_SMS_changes

---

database/apidocs/changelog/core-api-release-3590.json

Added Core API Release 35.9.0 initially removed to resolve conflicts

Added Core API Release 35.9.0 initially removed to resolve conflicts

---

database/apidocs/apis/v2/customer-identity-api/account/multipurpose-token-and-sms-otp-generation-api/multipurpose-email-token-generation.json
database/apidocs/apis/v2/customer-identity-api/account/multipurpose-token-and-sms-otp-generation-api/multipurpose-sms-otp-generation.json
database/apidocs/changelog/core-api-release-3590.json

Priority release due to **minor yet important** corrections made to the **New Multi Token Generation** APIs.
- [Multipurpose Email Token Generation](https://apidocs-dev.div4.dev/api/v2/customer-identity-api/account/multipurpose-token-and-sms-otp-generation-api/multipurpose-email-token-generation/) API
- [Multipurpose SMS OTP Generation](https://www.loginradius.com/docs/api/v2/customer-identity-api/account/multipurpose-token-and-sms-otp-generation-api/multipurpose-sms-otp-generation/) API

Dev to Staging (1 August 2023)

---

database/apidocs/apis/v2/customer-identity-api/account/multipurpose-token-and-sms-otp-generation-api/multipurpose-email-token-generation.json
database/apidocs/apis/v2/customer-identity-api/account/multipurpose-token-and-sms-otp-generation-api/multipurpose-sms-otp-generation.json
database/apidocs/changelog/core-api-release-3590.json

Priority release due to **minor yet important** corrections made to the **New Multi Token Generation** APIs.
- [Multipurpose Email Token Generation](https://apidocs-dev.div4.dev/api/v2/customer-identity-api/account/multipurpose-token-and-sms-otp-generation-api/multipurpose-email-token-generation/) API
- [Multipurpose SMS OTP Generation](https://www.loginradius.com/docs/api/v2/customer-identity-api/account/multipurpose-token-and-sms-otp-generation-api/multipurpose-sms-otp-generation/) API

Staging to Main (1 August 2023)

---

database/supportdocs/docs/libraries/mobile-sdk-libraries/ios-library.md

Updated a path under the Setup Pre-requisites section of the iOS library document.
- **Removed:** Admin Console -> Deployment > Configuration > Apps for Social Login to work properly
- **Added:** [Admin Console > Deployment > Apps > Web Apps](https://adminconsole.loginradius.com/deployment/apps/web-apps)

Minor change in the IOS SDK library document

---

database/supportdocs/docs/libraries/mobile-sdk-libraries/ios-library.md

Added a full stop "." with respect to https://github.com/LoginRadius/apidocs/pull/348 to check the Pipeline.

Pipeline Check

---

database/apidocs/changelog/core-api-release-3610.json
database/apidocs/menus/posts.json

Changelog for **Core API Release 36.1.0**.

Changelog for Core API Release 36.1.0

---

database/apidocs/changelog/js-release-3210.json

Minor case correction in the changelog.

Minor correction in Changelog

---

database/apidocs/apis/v2/customer-identity-api/social-login/native-social-login-api/access-token-by-custom-jwt-token.json
database/apidocs/menus/v2.json

Created Access Token via Custom JWT Token API

Created Access Token via Custom JWT Token API

---

database/apidocs/apis/v2/customer-identity-api/social-login/native-social-login-api/access-token-by-custom-jwt-token.json

Access Token via Custom JWT Token API (Update)

Change_in_Access_Token_via_Custom_JWT_Token_API

---

database/apidocs/changelog/core-api-release-3610.json

added_link_in_changelog

---

database/apidocs/apis/v2/customer-identity-api/configuration/get-server-time.json
database/apidocs/apis/v2/customer-identity-api/consent-management/consent-by-access-token.json
database/apidocs/apis/v2/customer-identity-api/consent-management/consent-by-consent-token.json
database/apidocs/apis/v2/customer-identity-api/consent-management/consent-log-by-access-token.json
database/apidocs/apis/v2/customer-identity-api/consent-management/update-consent-by-access-token.json
database/apidocs/apis/v2/customer-identity-api/consent-management/verify-consent-by-access-token.json
database/apidocs/apis/v2/customer-identity-api/custom-object/create-custom-object-by-token.json
database/apidocs/apis/v2/customer-identity-api/custom-object/custom-object-by-objectrecordid-and-token.json
database/apidocs/apis/v2/customer-identity-api/custom-object/custom-object-by-token.json
database/apidocs/apis/v2/customer-identity-api/custom-object/custom-object-delete-by-objectrecordid-and-token.json
database/apidocs/apis/v2/customer-identity-api/custom-object/custom-object-delete-by-objectrecordid-and-uid.json
database/apidocs/apis/v2/customer-identity-api/custom-object/custom-object-update-by-objectrecordid-and-token.json
database/apidocs/apis/v2/customer-identity-api/custom-object/custom-object-update-by-objectrecordid-and-uid.json
database/apidocs/apis/v2/customer-identity-api/passwordless-login/passwordless-login-by-email.json
database/apidocs/apis/v2/customer-identity-api/passwordless-login/passwordless-login-by-username.json
database/apidocs/apis/v2/customer-identity-api/passwordless-login/passwordless-login-phone-verification.json
database/apidocs/apis/v2/customer-identity-api/passwordless-login/passwordless-login-verify-by-email-and-otp.json
database/apidocs/apis/v2/customer-identity-api/passwordless-login/passwordless-login-verify-by-username-and-otp.json
database/apidocs/apis/v2/customer-identity-api/refresh-token/refresh-access-token-by-refresh-token.json
database/apidocs/apis/v2/customer-identity-api/refresh-token/refresh-token.json
database/apidocs/apis/v2/customer-identity-api/refresh-token/revoke-all-refresh-token.json
database/apidocs/apis/v2/customer-identity-api/refresh-token/revoke-refresh-token.json
database/apidocs/apis/v2/customer-identity-api/session/active-session-by-account-id-and-profile-id.json
database/apidocs/apis/v2/customer-identity-api/session/active-session-by-account-id.json
database/apidocs/apis/v2/customer-identity-api/session/active-session-by-profile-id.json
database/apidocs/apis/v2/customer-identity-api/session/generate-sott-token.json
database/apidocs/apis/v2/customer-identity-api/session/get-active-session-details.json
database/apidocs/apis/v2/customer-identity-api/session/invalidate-access-token.json
database/apidocs/apis/v2/customer-identity-api/session/validate-access-token.json
database/apidocs/menus/v2.json

Made minor corrections in **formatting**, **spelling**, and **links** for **29 Customer Identity APIs**.

Review the Customer Identity APIs

---

database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/email-authenticator/reset-mfa-email-otp-authenticator-settings-by-access-token.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/email-authenticator/reset-mfa-email-otp-authenticator-settings-by-uid.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/email-authenticator/verify-mfa-email-otp-by-access-token.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/google-authenticator/mfa-validate-google-auth-code.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/mfa-phone-login.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/security-question-authenticator/delete-reset-mfa-security-question-authenticator-settings.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/sms-authenticator/mfa-validate-otp.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/sms-authenticator/update-mfa-setting.json
database/apidocs/apis/v2/customer-identity-api/phone-authentication/phone-forgot-password-by-otp.json
database/apidocs/apis/v2/customer-identity-api/phone-authentication/phone-number-availability.json
database/apidocs/apis/v2/customer-identity-api/phone-authentication/phone-number-update.json
database/apidocs/apis/v2/customer-identity-api/phone-authentication/phone-resend-otp-by-token.json
database/apidocs/apis/v2/customer-identity-api/phone-authentication/phone-reset-password-by-otp.json
database/apidocs/apis/v2/customer-identity-api/phone-authentication/phone-verify-otp-by-token.json
database/apidocs/apis/v2/customer-identity-api/phone-authentication/phone-verify-otp.json
database/apidocs/apis/v2/customer-identity-api/phone-authentication/remove-phone-id-by-access-token.json
database/apidocs/apis/v2/customer-identity-api/pin-authentication/login-by-pin.json
database/apidocs/apis/v2/customer-identity-api/roles-management/delete-permissions-from-context.json
database/apidocs/apis/v2/customer-identity-api/roles-management/delete-role-from-context.json
database/apidocs/apis/v2/customer-identity-api/roles-management/delete-role.json
database/apidocs/apis/v2/customer-identity-api/roles-management/get-context.json
database/apidocs/apis/v2/customer-identity-api/roles-management/get-roles-by-uid.json
database/apidocs/apis/v2/customer-identity-api/roles-management/roles-create.json
database/apidocs/apis/v2/customer-identity-api/roles-management/roles-list.json
database/apidocs/apis/v2/customer-identity-api/roles-management/upsert-context.json
database/apidocs/apis/v2/customer-identity-api/step-up-authentication/mfa/mfa-step-up-authentication-by-email-otp.json
database/apidocs/apis/v2/customer-identity-api/step-up-authentication/mfa/send-mfa-step-up-auth-email-otp-by-access-token.json
database/apidocs/apis/v2/customer-identity-api/step-up-authentication/pin/step-up-auth-by-pin.json
database/apidocs/apis/v2/customer-identity-api/step-up-authentication/step-up-auth-by-password.json

Made minor corrections in the formatting and rectified a few URLs.

Minor corrections in formatting

---

database/apidocs/changelog/admin-console-release-25111.json
database/apidocs/menus/posts.json

Changelog for Admin Console Release 25.11.1

Changelog for Admin Console Release 25.11.1

---

database/supportdocs/docs/single-sign-on/tutorial/custom-identity-providers/custom-jwt-provider.md

Added a note, an image, and some detailed descriptions about the newly introduced options.

Added information about the new options provided.

---

database/supportdocs/docs/single-sign-on/tutorial/web-sso/overview.md

change in web sso document

---

database/apidocs/docs/v2/getting-started/data-points/detailed-data-points.md

Added description for the necessary profile data points.

Added description for a few profile data points

---

database/supportdocs/docs/authentication/concepts/password-hashing-and-salting.md
database/supportdocs/docs/security/platform-security/cryptographic-hashing-algorithms.md

Added the two new algorithms in the document.

Added details of the new algorithm

---

database/apidocs/docs/v2/admin-console/platform-configuration/standard-login/email-templates.md

API_alined_for_tokan_type

---

database/apidocs/changelog/core-api-release-3620.json

Removed a specific point that was not required to be pushed in this changelog.

Made updates to the changelog by excluding a specific point

---

database/apidocs/docs/v2/admin-console/platform-security/captcha-providers/google-recaptcha-configuration.md

Added a note regarding the triggering of V3 reCAPTCHA in the document.

Google V3 reCAPTCHA

---

database/apidocs/docs/v2/getting-started/data-points/detailed-data-points.md

Updated the Data field Description

Updated the Data field Description

---

database/apidocs/docs/v2/getting-started/data-points/detailed-data-points.md

#2 updated the data points description

#2 updated the data points description

---

database/supportdocs/docs/single-sign-on/tutorial/federated-sso/oauth-2-0/oauth-2-0-overview.md

Updated a few of the endpoints for Oauth2.0.

Updated endpoints for OAuth2.0

---

database/apidocs/docs/v2/getting-started/data-points/detailed-data-points.md

Updated the description of the data field Quote.

Updated the description of data field Quote.

---

database/apidocs/changelog/admin-console-release-25112.json
database/apidocs/menus/posts.json

Changelog for Admin Console Release 25.11.2

Changelog for Admin Console Release 25.11.2

---

database/apidocs/docs/v2/admin-console/platform-security/risk-based-auth.md
database/apidocs/docs/v2/customer-identity-api/multi-factor-authentication/MFA-with-Risk-Based-Authentication.md

Changes associated with Admin Console Release 25.11.2

Changes associated with Admin Console Release 25.11.2

---

database/apidocs/docs/v2/getting-started/data-points/detailed-data-points.md

Minor formatting changes in Profile Data Points doc

Minor formatting changes

---

database/apidocs/docs/v2/customer-identity-api/multi-factor-authentication/MFA-with-Risk-Based-Authentication.md

Changes associated with the Admin Console Release 25.11.2

Changes associated with the Admin Console Release 25.11.2

---

database/apidocs/docs/v2/getting-started/data-points/data-points.md

Corrected the url in the data points document

Minor updates in URL

---

database/apidocs/apis/v2/customer-identity-api/authentication/auth-read-profiles-by-token.json

Added a parameter for Auth Read All Profiles by Token API.

Added a parameter for this API

---

database/supportdocs/docs/libraries/mobile-sdk-libraries/ios-library.md

Updated the iOS Library Document.

Updated iOS Library Document as per iOS SDK version 5.9.0

---

database/apidocs/changelog/admin-console-release-25113.json
database/apidocs/menus/posts.json

Added an AutoLookup feature under the Custom IDPs automatically redirects a user to the specific Identity Provider (IdP) after entering an email ID with the respective domain name.

Changelog for Admin Console Release 25.11.3

---

database/apidocs/docs/v2/customer-identity-api/session/user-session-device-location.md

Added a new section of Usecase to disable concurrent access from multiple devices.

Added UseCase

---

database/apidocs/docs/v2/customer-identity-api/session/user-session-device-location.md

Corrected the API name and some minor formatting changes,

Minor corrections

---

database/apidocs/apis/v2/customer-identity-api/configuration/get-configurations.json

Updated the sample response of Get Configuration API

Config_API_changes_for_autolookup

---

database/apidocs/apis/v2/customer-identity-api/authentication/auth-forgot-password.json

Changed the resetpasswordurl parameter to optional in the Auth Forgot Password API

Minor correction in Auth Forgot Password API

---

database/apidocs/apis/v2/customer-identity-api/pin-authentication/forgot-pin-by-phone.json

Made minor formatting changes in the Forgot PIN By Phone

Minor updates in the Forgot PIN By Phone API

---

database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/mfa-validate-access-token.json

Removed the access_token from the query_parameter as it is being passed in the header of the MFA Settings By Access Token API

Minor updates in MFA API

---

database/supportdocs/docs/authentication/faq/troubleshooting.md
database/supportdocs/docs/governance/data-schema.md

Added new FAQs to the troubleshooting section and a note regarding the character limit on profile fields.

Added new Faqs and a note

---

database/supportdocs/docs/integrations/client-side-connectors/intercom.md

Corrected the URL in the intercom document

Corrected URL

---

database/apidocs/docs/v2/customer-identity-api/advanced-api-usage.md

added link to the Security Question section of the Admin Console in

added link to relevant section of admin console

---

database/apidocs/changelog/js-release-3230.json
database/apidocs/menus/posts.json

Added the changelog for V2JS Release 3.23.0.

changelog for V2JS Release 3.23.0

---

database/apidocs/docs/v2/customer-identity-api/consent-mangement/overview.md

Corrected a spelling mistake in the document.

Minor correction

---

database/apidocs/docs/v2/customer-identity-api/consent-mangement/overview.md

Removed the Passwordless Login note and added the Consent Management note in the Consent Management document

Minor Correction in Consent Management

---

plugins/routing/redirections/urls.json

Handled a redirection for a 404 error

404 Link Fix

---

database/apidocs/docs/v2/single-sign-on/Machine-to-Machine/overview.md

Made a minor update regarding the token lifetime in the document.

Minor update

---

database/supportdocs/docs/single-sign-on/tutorial/federated-sso/overview.md

Removed the WS Federation section from the Federated SSO overview document.

WS Federation

---

database/apidocs/changelog/admin-console-release-25114.json
database/apidocs/menus/posts.json

Changelog for Admin Console Release 25.11.4

Admin Console Release 25.11.4

---

database/supportdocs/docs/customer-management/profile-view.md

Added new functionalities after clicking on the manage button

Made the detailed options after clicking the manage button

---

database/supportdocs/docs/single-sign-on/tutorial/federated-sso/saml/idp-initiated.md
database/supportdocs/docs/single-sign-on/tutorial/federated-sso/saml/sp-initiated.md

Updated the SAML UI configuration.

Added details for SAML Assertion NotOnOrAfter

---

database/supportdocs/docs/single-sign-on/tutorial/custom-identity-providers/pre-built-connections.md
database/supportdocs/docs/single-sign-on/tutorial/federated-sso/pre-built-connections.md
database/supportdocs/menus/sidebar.json
plugins/routing/redirections/urls.json

Pre-Built Custom IDP & Federated SSO

ch_DOC_2775_PreBuiltCustomIDPFedSSO

---

database/apidocs/changelog/core-api-release-3640.json
database/apidocs/menus/posts.json

Changelog for Core API Release 36.4.0

Core API Release 36.4.0

---

database/supportdocs/docs/single-sign-on/tutorial/web-sso/overview.md

Minor updates in the output format of the setToken Ajax call and added the Ajax Call for the setcustomtoken.

Ajax Call Output Format

---

database/supportdocs/docs/single-sign-on/tutorial/federated-sso/saml/idp-initiated.md
database/supportdocs/docs/single-sign-on/tutorial/federated-sso/saml/sp-initiated.md

Added the NotOnOrAfter field in the SAML SP and IP initiated configuration

SAML IP and SP Initiated

---

plugins/routing/redirections/urls.json

Reverted URL Redirection as the updated links were released on Production

Revert URL Redirection

---

database/apidocs/apis/v2/customer-identity-api/authentication/auth-update-profile-by-token.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/mfa-email-login.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/sms-authenticator/mfa-update-phone-number.json
database/apidocs/apis/v2/customer-identity-api/phone-authentication/phone-login.json
database/apidocs/apis/v2/customer-identity-api/phone-authentication/phone-user-registration-by-sms.json

New parameter added to prevent sms in case of optional flow

Updated the preventverificationsms in the APIs

---

database/supportdocs/docs/single-sign-on/overview.md

Removed occurrences of WS Federation

WS Federation Removal

---

database/apidocs/docs/v2/admin-console/social-provider/supported-social-networks.md

Updated the social provider list by removing the unsupported providers and changing the URL accordingly

Updated Social Provider List

---

database/apidocs/docs/v2/admin-console/platform-security/regulations.md
database/supportdocs/docs/authentication/faq/age-verification.md

Updates in Age Verification document

Updates in Age Verification

---

database/apidocs/docs/v2/getting-started/supported-certificate-authorities.md
database/apidocs/menus/v2.json

Added a new document with a list of SSL certificate authorities supported by LoginRadius.

Supported SSL Certificate Authorities

---

database/supportdocs/docs/integrations/available-integrations.md

Updated a few logos for integrations.

Updated Logos for Integration

---

theme/apidocs/assets/stylesheets/less/style.less
theme/apidocs/assets/stylesheets/style.css

Fixes for Night Mode

---

database/apidocs/docs/v2/admin-console/overview.md
database/supportdocs/docs/authentication/faq/billing-faq.md

Added more information for the billing section and updated the billing FAQ on how to update credit card details.

Billing Information

---

database/apidocs/menus/v2.json
database/supportdocs/docs/libraries/command-line-interface/cli.md
database/supportdocs/menus/sidebar.json
plugins/routing/redirections/urls.json
theme/apidocs/includes/header.php
theme/apidocs/includes/support_header.php

Position changes related to CLI document.

Changes related to CLI document

---

plugins/routing/redirections/urls.json

Handled redirection for the PHP library

Redirection Handling

---

database/supportdocs/docs/single-sign-on/overview.md

Updated the images and added links in table form.

Changed image and applied link in the correct form

---

plugins/night-mode/assets/css/nightmode.css

Changed the background color of the RSS feed section in the changelog and fixed the API enter button color mismatch issue

Changed the background color of the RSS feed section in the changelog

---

plugins/routing/redirections/urls.json

Redirecting 404 Handled

---

database/apidocs/docs/v2/admin-console/platform-configuration/communication-configuration/sms/providers/custom-sms-provider.md

Updated the Custom SMS/Text Providers document

Updated the Custom SMS/Text Providers document

---

database/apidocs/apis/v2/customer-identity-api/step-up-authentication/mfa/step-up-auth-by-google-authenticator-code.json

Corrected a broken link for the Step-Up Authenticate by Google Authenticator Code API

Corrected Link

---

database/apidocs/apis/v2/api/auth-user-registration-by-email.json
database/apidocs/apis/v2/api/auth-user-registration-by-recaptcha.json
database/apidocs/apis/v2/customer-identity-api/authentication/auth-user-registration-by-email.json
database/apidocs/apis/v2/customer-identity-api/authentication/auth-user-registration-by-recaptcha.json
database/apidocs/changelog/core-api-release-3650.json

Minor update in the field description of the API

Minor update in the field description of the API

---

database/apidocs/changelog/admin-console-release-25120.json
database/apidocs/menus/posts.json

Changelog - Admin Console Release 25.12.0

Changelog - Admin Console Release 25.12.0

---

database/apidocs/menus/v2.json
plugins/routing/redirections/urls.json

Fixed URLs with 404

---

database/apidocs/menus/v2.json
plugins/routing/redirections/urls.json

Reverts LoginRadius/apidocs#550

Revert "Fixed URLs with 404"

---

database/supportdocs/docs/single-sign-on/tutorial/federated-sso/openid-connect/openid-connect-overview.md

Multiapp OIDC changes

---

database/supportdocs/docs/single-sign-on/tutorial/federated-sso/oauth-2-0/oauth-2-0-overview.md

OAuth 2.0 MultiApp Implementation Updates

OAuth 2.0 MultiApp Implementation Updates

---

database/apidocs/apis/v2/customer-identity-api/authentication/auth-change-password.json
database/apidocs/apis/v2/customer-identity-api/authentication/auth-forgot-password.json
database/apidocs/apis/v2/customer-identity-api/authentication/auth-login-by-username.json
database/apidocs/apis/v2/customer-identity-api/authentication/auth-update-profile-by-token.json
database/apidocs/apis/v2/customer-identity-api/phone-authentication/phone-forgot-password-by-otp.json
database/apidocs/apis/v2/customer-identity-api/phone-authentication/phone-login.json

Added g-recaptcha-response parameter in API protected under BOT Protection feature

Added g-recaptcha-response parameter in API protected under BOT Protection feature

---

database/supportdocs/docs/authentication/tutorial/passwordless-login.md

Added content related to token type in passwordless login document

Added content related to token type in passwordless login document

---

database/supportdocs/docs/authentication/quick-start/sso-implementation.md

updated SSO doc

---

database/apidocs/docs/v2/getting-started/implementation-workflows.md
database/apidocs/docs/v2/getting-started/security-best-practice.md

Refined the content and converted hard links to soft links

Minor Updates

---

database/apidocs/docs/v2/customer-identity-api/account/account-overview.md

Updated the Account Overview doc

Minor changes in Account Overview Doc

---

database/apidocs/changelog/admin-console-release-25130.json
database/apidocs/menus/posts.json

Changelog for Admin Console Release 25.13.0

Changelog for Admin Console Release 25.13.0

---

database/supportdocs/docs/authentication/tutorial/phone-login.md
database/supportdocs/docs/integrations/available-integrations.md

Added the new delete user template and changed screenshots

Phone Login Update

---

database/apidocs/docs/v2/admin-console/platform-configuration/standard-login/email-templates.md

A new placeholder tag, CurrentYear, has been added to display the current year.

New Placeholder Tag

---

database/apidocs/changelog/core-api-release-3660.json
database/apidocs/menus/posts.json

Core API v36.6.0 Changelog

---

database/apidocs/apis/v2/customer-identity-api/configuration/get-configurations.json

Added Push Authenticator details in config API

Added Push Authenticator details in config API

---

config.php
web.config

[apidocs-dev.div4.dev](http://apidocs-dev.div4.dev/) -> [apidocs-dev.lr-dev.dev](http://apidocs-dev.lr-dev.dev/)

Updated dev domain

---

database/supportdocs/docs/single-sign-on/tutorial/custom-identity-providers/pre-built-connections.md

Updated the [Custom IDP Pre-Built Integrations](https://www.loginradius.com/docs/single-sign-on/tutorial/custom-identity-providers/pre-built-connections/) document to conform with the updates in the Admin Console Release 25.13.1

Updated Custom IDP Pre-Built Integrations

---

database/apidocs/changelog/admin-console-release-25130.json

Admin Console Release 25.13.0 | Post Release Update

Admin Console Release 25.13.0 | Post Release Update

---

plugins/routing/redirections/urls.json

On-site Docs Errors

---

database/apidocs/apis/v2/customer-identity-api/account/multipurpose-token-and-sms-otp-generation-api/multipurpose-email-token-generation.json
database/apidocs/apis/v2/customer-identity-api/account/multipurpose-token-and-sms-otp-generation-api/multipurpose-sms-otp-generation.json
database/apidocs/docs/v2/customer-identity-api/account/multipurpose-token-and-sms-otp-generation-api/multipurpose-sms-otp-generation-overview.md

https://loginradius.atlassian.net/browse/DOC-2904

Fixed the mistakes in the above API docs

---

plugins/routing/redirections/urls.json

Corrected Redirection Post Release

Corrected Redirection Post Release

---

database/supportdocs/docs/single-sign-on/tutorial/federated-sso/oauth-2-0/oauth-2-0-overview.md
database/supportdocs/docs/single-sign-on/tutorial/federated-sso/openid-connect/openid-connect-overview.md

Corrected formatting issues

---

database/supportdocs/docs/security/platform-security/social-data-compliance.md

Monthly 404 Link check (July)

---

database/supportdocs/docs/authentication/concepts/password-policy.md

Added the Breached Password Protection section and changed all the screenshots in the document

Breached Password Protection

---

database/apidocs/docs/v2/getting-started/implementation-workflows.md

Updated the hyperlink in the [Implementation Workflows](https://www.loginradius.com/docs/api/v2/getting-started/implementation-workflows/) document.
**Existing:** [Identity Experience Framework Customizations](https://www.loginradius.com/docs/api/v2/user-registration/hosted-registration)
**Redirected To:** https://www.loginradius.com/docs/libraries/identity-experience-framework/customization/

Updated the hyperlink in Implementation Workflows document

---

plugins/js-search/search.php

Converted to Environment Variables

Removed Algolia Key from Public Repo

---

database/apidocs/apis/v2/customer-identity-api/passwordless-login/passwordless-login-by-email.json
database/apidocs/apis/v2/customer-identity-api/passwordless-login/passwordless-login-by-phone.json
database/apidocs/apis/v2/customer-identity-api/passwordless-login/passwordless-login-by-username.json

Add g-recaptcha-response in Passwordless Login APIs

Add g-recaptcha-response in Passwordless Login APIs

---

database/apidocs/docs/v2/customer-identity-api/overview.md

Minor correction in terms of labels

Update the Overview document under Customer Identity API

---

database/apidocs/docs/v2/getting-started/response-codes/customer-identity-api-codes.md

Duo Authentication - Adding Error Codes

Duo Authentication - Adding Error Codes

---

database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/duo-security-authenticator/mfa-re-authentication-by-duo-security-authenticator.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/duo-security-authenticator/mfa-verify-duo-security-authenticator-by-access-token.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/duo-security-authenticator/mfa-verify-duo-security-authenticator-by-mfa-token.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/duo-security-authenticator/reset-mfa-duo-security-authenticator-settings-by-uid.json
database/apidocs/apis/v2/customer-identity-api/multi-factor-authentication/duo-security-authenticator/reset-mfa-duo-security-authenticator-settings.json
database/apidocs/docs/v2/customer-identity-api/multi-factor-authentication/duo-security-authenticator/overview.md
database/apidocs/menus/v2.json

Adding New APIs and Overview Document for Duo Authentication

Adding New APIs and Overview Document for Duo Authentication

---

database/supportdocs/docs/libraries/js-libraries/advanced-js-customizations.md

Added JavaScript-related description for Duo MFA

Added JavaScript related description for Duo MFA

---

plugins/routing/redirections/urls.json

Added redirection from `https://www.loginradius.com/docs/customer-management/` to `https://www.loginradius.com/docs/customer-management/overview/ `

Handling 404 Redirection

---

database/apidocs/apis/v2/customer-identity-api/passkey/Forgot-Passkey.json
database/apidocs/apis/v2/customer-identity-api/passkey/Login-Reset-passkey-begin.json
database/apidocs/apis/v2/customer-identity-api/passkey/Login-Reset-passkey-finish.json
database/apidocs/apis/v2/customer-identity-api/passkey/Manage-List-users-passkeys.json
database/apidocs/apis/v2/customer-identity-api/passkey/Manage-Remove-passkey-by-Uid.json
database/apidocs/menus/v2.json

Added 5 new passkey APIs and improvements

Added 5 new passkey APIs and improvements

---

database/apidocs/apis/v2/single-sign-on/federated-sso/oauth-2-0/oauth-token-by-loginradius-guid-jwt-encrypted-token.json
database/apidocs/apis/v2/single-sign-on/federated-sso/openid-connect/oidc-token-by-loginradius-guid-jwt-encrypted-token.json
database/apidocs/menus/v2.json

Following are the APIs that have been added under **Single Sign-On > Federated SSO > OAuth 2.0/OpenID Connect**
- OIDC Token By LoginRadius GUID/JWT Encrypted Token
- OAuth Token By LoginRadius GUID/JWT Encrypted Token

Added 2 New APIs in OIDC/OAuth Flow

---

database/apidocs/menus/v2.json

Corrections

---

database/apidocs/apis/v2/single-sign-on/federated-sso/oauth-2-0/oauth-token-by-loginradius-guid-jwt-encrypted-token.json
database/apidocs/apis/v2/single-sign-on/federated-sso/openid-connect/oidc-token-by-loginradius-guid-jwt-encrypted-token.json
database/apidocs/menus/v2.json

Final Corrections in the OIDC OAuth Flow APIs

Final Corrections in the OIDC OAuth Flow APIs

---

database/apidocs/docs/v2/admin-console/platform-configuration/communication-configuration/email/global-email-settings.md
database/apidocs/docs/v2/admin-console/platform-configuration/communication-configuration/sms/global-sms-settings.md
database/apidocs/docs/v2/admin-console/platform-configuration/passwordless-login-configuration.md
database/supportdocs/docs/authentication/concepts/email-communications.md
database/supportdocs/docs/authentication/concepts/sms-communication.md
database/supportdocs/docs/authentication/tutorial/passwordless-login.md
database/supportdocs/docs/authentication/tutorial/phone-login.md

Corrections associated with adding details on Request Period

Corrections associated with adding details on Request Period

---

database/apidocs/docs/v2/getting-started/response-codes/customer-identity-api-codes.md

**Summary:** Added Passkey-Related Error Codes 1320 to 1329
**Breakdown:** 
- 1320 to 1326 and 1329 (_Previously Skipped in Core API Release v36.8.0_)
- 1227 and 1228 (_Added in Core API Release v36.11.0_)

Added Passkey-Related Error Codes

---

database/supportdocs/docs/single-sign-on/tutorial/federated-sso/openid-connect/openid-connect-overview.md

Fixed the formatting of the note in the OpenID Connect Document

Fixed Note in OpenID Connect Document

---

database/supportdocs/docs/authentication/concepts/session-management.md

Added Introduction of Restrict Login Sharing Feature

Added Introduction of Restrict Login Sharing Feature

---

database/apidocs/changelog/core-api-release-36110.json
database/apidocs/menus/posts.json

Added Changelog for  Core API Release v36.11.0

Ch doc 2995 changelog for core api release36110

---

database/apidocs/apis/v2/customer-identity-api/step-up-authentication/send-email-otp-for-step-up-auth-without-mfa.json
database/apidocs/apis/v2/customer-identity-api/step-up-authentication/verify-email-otp-for-step-up-auth-without-mfa.json

Added two new APIs for step-up authentication without MFA

Add two new APIs for step-up authentication without MFA

---

database/apidocs/apis/v2/customer-identity-api/step-up-authentication/send-email-otp-for-step-up-auth-without-mfa.json

Correction - Added header attribute

Correction - Added header attribute

---

database/apidocs/docs/v2/customer-identity-api/step-up-authentication/overview.md

Brief overview of newly added Step-Up APIs that works without MFA

Brief overview of newly added Step-Up APIs that works without MFA

---

database/apidocs/apis/v2/customer-identity-api/step-up-authentication/send-email-otp-for-step-up-auth-without-mfa.json
database/apidocs/apis/v2/customer-identity-api/step-up-authentication/verify-email-otp-for-step-up-auth-without-mfa.json
database/apidocs/changelog/core-api-release-36111.json
database/apidocs/menus/posts.json

Changelog associated with Core API Release 36.11.1

Changelog associated with Core API Release 36.11.1

---

database/apidocs/apis/v2/customer-identity-api/social-login/social-login-by-ping.json
database/apidocs/docs/v2/customer-identity-api/social-login/getting-started.md

Fixed the description of ClientGUID

Fixed the description of ClientGUID

---

database/apidocs/changelog/core-api-release-36120.json
database/apidocs/menus/posts.json

Changelog for Core API Release 36.12.0

Changelog for Core API Release 36.12.0

---

database/apidocs/apis/v2/integrations/webhooks/create-webhook-subscription.json
database/apidocs/apis/v2/integrations/webhooks/delete-webhook-subscription.json
database/apidocs/apis/v2/integrations/webhooks/get-webhook-subscription-details.json
database/apidocs/apis/v2/integrations/webhooks/list-all-events.json
database/apidocs/apis/v2/integrations/webhooks/list-all-webhooks.json
database/apidocs/apis/v2/integrations/webhooks/update-webhook-subscription.json
database/apidocs/changelog/core-api-release-36120.json
database/apidocs/menus/v2.json
database/supportdocs/docs/authentication/tutorial/username-login.md

Added Six Webhook APIs (_Management_)

Added Six Webhook APIs (Management)

---

theme/apidocs/includes/header.php
theme/apidocs/includes/support/header.php
theme/apidocs/includes/support_header.php

Reverts LoginRadius/apidocs#984

Revert "Staging"

---

theme/apidocs/includes/header.php
theme/apidocs/includes/support/header.php
theme/apidocs/includes/support_header.php

Reverts LoginRadius/apidocs#985

Revert "Revert "Staging""

---

database/supportdocs/docs/customer-intelligence/login-analytics.md

Updated the term Monthly/Daily Active Customers to Monthly/Daily Active Accounts

Update Monthly/Daily Active Customers to Monthly/Daily Active Accounts
